version: 0.2

phases:
    build:
        commands:
        # install npm modules
        - npm i

        # replace index.html with empty string
        - sed -i -- 's/index.html//g' index.html

        # replace guide href with prod version
        - sed -i -- 's/"backToRoadMapLink" href="\/"/"backToRoadMapLink" href="\/guides\/learning-roadmap\/"/g' ./**/index.html

        # copy the learning guide index
        - cp -i ./index.html /efs/www/frontendmasters.com/learning-roadmap/  

        # copy the guides
        - cp -r ./* /efs/www/frontendmasters.com/learning-roadmap/

        # make nginx the owner of the guides, doesn't work in codebuild
        # - chown -hR nginx:nginx /efs/www/frontendmasters.com/learning-roadmap/
